### ISSUE TITLE
Different results between get_inat_obs() and iNaturalist explore page

### ISSUE THREAD

**Issue by kang37** [ropensci/rinat#58]
I am trying to download observations by research areas. I found the results of get_inat_obs() is different from the results of iNaturalist explore page searching. 
Take a island (Yakushima island in Japan) as the example. If we use the function, we get the following results. There are 32 observations covering 31 species in 2022, the numbers become 8 and 8 when we only keep the research grade data. 
```
# Get all the observation data in 2022. 
obs_yakushima_2022 <- get_inat_obs(
  query = "Yakushima, Kagoshima, Japan", year = 2022, maxresults = 10000
)
nrow(obs_yakushima_2022)
# 32
length(unique(obs_yakushima_2022$scientific_name))
# 31

# If we only want the research grade data. 
obs_yakushima_2022_research <- get_inat_obs(
  query = "Yakushima, Kagoshima, Japan", year = 2022, quality = "research", 
  maxresults = 10000
)
nrow(obs_yakushima_2022_research)
# 8
length(unique(obs_yakushima_2022_research$scientific_name))
# 8
```

However, if we do the inquiry on iNaturalist explore page, we get 163 observations covering 118 species in 2022. If we filter the data to keep the research grade data, we have 73 observations, covering 55 species. 
<img width="1378" alt="image" src="https://github.com/ropensci/rinat/assets/51525392/86da0c06-a8d9-4f71-b45a-4a6bdeae975b">
<img width="1377" alt="image" src="https://github.com/ropensci/rinat/assets/51525392/b0bfe6cc-90f8-4d48-8fd9-dc435b2dd602">
<img width="1386" alt="image" src="https://github.com/ropensci/rinat/assets/51525392/5086ec4c-dfc4-4a1c-8717-92bfdb78f02d">

Is there anyway to get the observation data of the iNaturalist explore pages?

**Comment by stragu** [comment]
> Just in case this is still useful to anyone, rather than put the place in the `query` param, you should use either `bounds` with coordinates, or the `place_id`.

Indeed, thank you for the reply.
The "query" argument will search in any string, and in this case it will most likely match the "place_guess" field.
[The search on iNaturalist](https://www.inaturalist.org/observations?d1=2022-01-01&d2=2022-12-31&place_id=34090&subview=map) has more records because some of them have the place guess written in a different language / script to English. For example, [this observation](https://www.inaturalist.org/observations/202519506) has "日本、鹿児島県熊毛郡屋久島町 屋久島".

The `place_id` for that location is 34090, so the following command should return the same results (with two extra observations that have the "casual" `quality_grade`):

```r
obs_yakushima_2022 <- get_inat_obs(place_id = 34090,
                                   year = 2022,
                                   maxresults = 10000)
```
